export const category = [
  { label: "Bangles", name: "bangles" },
  { label: "Bra", name: "bra" },
  { label: "Comb", name: "comb" },
  { label: "Conditioner", name: "conditioner" },
  { label: "Cream", name: "cream" },
  { label: "Deo", name: "deo" },
  { label: "Detergent", name: "detergent" },
  { label: "Diapers", name: "diapers" },
  { label: "Face Wash", name: "face-wash" },
  { label: "Hair Color", name: "hair-color" },
  { label: "Hancky", name: "hancky" },
  { label: "Lotion", name: "lotion" },
  { label: "Mehendi", name: "mehendi" },
  { label: "Nail Polish", name: "nail-polish" },
  { label: "Oil", name: "oil" },
  { label: "Other", name: "other" },
  { label: "Pad", name: "pad" },
  { label: "Perfume", name: "perfume" },
  { label: "Powder", name: "powder" },
  { label: "Shampoo", name: "shampoo" },
  { label: "Soap", name: "soap" },
  { label: "Socks", name: "socks" },
  { label: "Toothbrush", name: "toothbrush" },
  { label: "Toothpaste", name: "toothpaste" },
  { label: "Underwear", name: "underwear" },
];
